export const PROJECT_STATUS = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  APPROVED: 'APPROVED',
  DECLINED: 'DECLINED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  ACTIVE: 'active',
  PENDING: 'pending',
  INACTIVE: 'inactive',
};

export const PROJECT_CATEGORIES = [
  'TITHES & OFFERINGS',
  'BUILDING FUND',
  'MISSIONS',
  'EVENTS',
  'MEMBERSHIP',
];

export const MINISTRY_TYPES = [
  'WORSHIP',
  'YOUTH',
  'CHILDREN',
  'OUTREACH',
  'PRAYER',
  'HOSPITALITY',
  'MEDIA',
  'ADMINISTRATION',
];

export const GROUP_TYPES = [
  'BIBLE STUDY',
  'PRAYER GROUP',
  'FELLOWSHIP',
  'DISCIPLESHIP',
  'SPECIAL INTEREST',
];

